// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojlgfebwmrgkgloffsyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qbGdmZWJ3bXJna2dsb2Zmc3loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5ODQyNTAsImV4cCI6MjA1MDU2MDI1MH0.MF9l3lU-IVUITphDNbqGOt0IadnD-WEmVZRAn2Rkbko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);